cursor #e1e2eb
cursor_text_color #c2c6d5

foreground            #e1e2eb
background            #11131a
selection_foreground  #193057
selection_background  #b1c6f7
url_color             #adc6ff

color0   #11131a
color1   #ff7299
color2   #7fff92
color3   #fff872
color4   #94b1f2
color5   #304576
color6   #adc6ff
color7   #eff4ff
color8   #999da5
color9   #ff9fb9
color10  #a5ffb3
color11  #fffaa5
color12  #b9ceff
color13  #c5d7ff
color14  #dae5ff
color15  #f8faff
