cursor #f8dcd7
cursor_text_color #e3beb7

foreground            #f8dcd7
background            #1d100d
selection_foreground  #5c180b
selection_background  #ffb4a4
url_color             #ffb4a4

color0   #1d100d
color1   #ff7572
color2   #99ff7f
color3   #ffe472
color4   #f29c8a
color5   #763628
color6   #ffb4a4
color7   #fff2ef
color8   #a59b99
color9   #ffa19f
color10  #b7ffa5
color11  #ffeea5
color12  #ffbfb1
color13  #ffcabf
color14  #ffddd6
color15  #fff9f8
