cursor #e7e0ed
cursor_text_color #ccc3d7

foreground            #e7e0ed
background            #15121b
selection_foreground  #392366
selection_background  #d2bcff
url_color             #d2bcff

color0   #15121b
color1   #ff728e
color2   #7fff9a
color3   #ffda72
color4   #bea5f2
color5   #4f3d76
color6   #d2bcff
color7   #f4efff
color8   #9d99a5
color9   #ff9fb2
color10  #a5ffb8
color11  #ffe7a5
color12  #d8c6ff
color13  #dfd0ff
color14  #eae0ff
color15  #faf8ff
